### PR TITLE
fix(wizard): Handle missing auth token in wizard API endpoint response

### LINKED ISSUE #564: Handle missing auth token data more gracefully
(INC-727 Follow-up | ref #563)

The wizard expects a valid auth token when receiving the project selection response from the Sentry backend. INC-727 has shown that this isn't always the case so let's at least more gracefully handle this scenario. 

I see two possible ways:
1. Exit with a message that this is most likely a Sentry issue and should be reported via GH
2. Log a warning and continue without a valid auth token. Instead we set something like `authToken: "_ADD_YOUR_TOKEN_"`.

I think 2 is potentially possible but if we run into a lot of troubles with it, 1 is a good enough fallback.

### PR DESCRIPTION
**Pull request by Lms24**
This PR adjusts the `SentryProjectData` type to reflect that the wizard might not always receive an auth token (as we learned in INC-727). Consequently, we now handle not receiving an auth token and proceed with a dummy token and a warning for users instead:

image

closes #564

### CODE REVIEW

File: src/utils/clack-utils.ts [hunk 1]
```diff
@@ -726,6 +726,7 @@ export function isUsingTypeScript() {
   }
 }
 
+const DUMMY_AUTH_TOKEN = '_YOUR_AUTH_TOKEN_';
```
Comment (AbhiPrasad) [inline src/utils/clack-utils.ts:729]:
```suggestion
const DUMMY_AUTH_TOKEN = '_YOUR_SENTRY_AUTH_TOKEN_';
```

**Review by AbhiPrasad — APPROVED** [review]

File: src/utils/clack-utils.ts (hunk 1 above)
Comment (Lms24) [reply src/utils/clack-utils.ts]: good idea!

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,9 @@
 # Changelog
 
+## Unreleased
+
+- fix(wizard): Handle missing auth token in wizard API endpoint response
```
Comment (Lms24) [inline CHANGELOG.md:5]:
```suggestion
- fix(wizard): Handle missing auth token in wizard API endpoint response (#566)
```
