### PR TITLE
ref(sveltekit): Add vite plugin insertion fallback mechanism

### LINKED ISSUE #363: Sentry SvelteKit Wizard fails with "config.plugins.splice is not a function"
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which SDK are you using?

@sentry/sveltekit

### SDK Version

7.58.1

### Framework Version

SvelteKit 1.22.3

### Link to Sentry event

_No response_

### SDK Setup

```ts
Sentry.init({
    dsn: "<DSN>",
    tracesSampleRate: 1
})
```

### Steps to Reproduce

```sh
$ npx @sentry/wizard@latest -i sveltekit
```

### Expected Result

For the Sentry Sveltekit library to be installed correctly

### Actual Result

```sh
 npx @sentry/wizard@latest -i sveltekit
Running Sentry Wizard...
version: 3.7.1 | sentry-cli version: 1.75.2
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)
Skipping connection to Sentry due files already patched

┌   Sentry SvelteKit Wizard
│
◇   ──────────────────────────────────────────────────────────────╮
│                                                                 │
│  This Wizard will help you set up Sentry for your application.  │
│  Thank you for using Sentry :)                                  │
│                                                                 │
│  Version: 3.7.1                                                 │
│                                                                 │
├─────────────────────────────────────────────────────────────────╯
│
◇  Are you using Sentry SaaS or self-hosted Sentry?
│  Sentry SaaS (sentry.io)
│
◇  Do you already have a Sentry account?
│  Yes
│
●  If the browser window didn't open automatically, please open the following link to log into Sentry:
│
│  https://sentry.io/account/settings/wizard/<account>/
│
◇  Login complete.
│
◇  Select your Sentry project.
│  nemo-iv/nemo
│
◇  The @sentry/sveltekit package is already installed. Do you want to update it to the latest version?
│  Yes
│
◇  Updated @sentry/sveltekit with yarn.
✓ Successfully added the auth token to .sentryclirc
✓ .sentryclirc added to .gitignore
✓ Successfully created sentry.properties

│
▲  File hooks.client.ts already contains Sentry code.
│  Skipping adding Sentry functionality to hooks.client.ts.
│
▲  File hooks.server.ts already contains Sentry code.
│  Skipping adding Sentry functionality to hooks.server.ts.
│
■  Error while setting up the SvelteKit SDK:
│
●  TypeError: config.plugins.splice is not a function

🎉  Successfully set up Sentry for your project 🎉
```

CleanShot 2023-07-17 at 09 31 12@2x

### PR DESCRIPTION
**Pull request by Lms24**
As reported in #363 and #362, our automatic vite plugin insertion for `sentrySvelteKit` fails when more complex vite config syntax is encountered. We can't reasonably cover these more complex cases but previously we just let the wizard crash, which isn't great either. 

This PR now adds a fallback mechanism by showing a copy/paste-able snippet with the necessary vite config adjustments, just like we do it in the source maps wizard:

image

Closes #363
(#362 will be closed in a separate PR)

### CODE REVIEW

File: src/sveltekit/sdk-setup.ts [hunk 1]
```diff
@@ -415,28 +415,95 @@ async function modifyViteConfig(
...
-    index: 0,
-  });
+      index: 0,
+    });
+
+    const code = generateCode(viteModule.$ast).code;
+
+    await fs.promises.writeFile(viteConfigPath, code);
+  } catch (e) {
+    // TODO: log e if --debug is set?
```
Comment (Lms24) [inline src/sveltekit/sdk-setup.ts:441]: Will take care of this in a follow-up PR, as we need to bring the `--debug` flag into the clack-based wizard options first

Comment (Lms24) [reply src/sveltekit/sdk-setup.ts:441]: #381

**Review by AbhiPrasad — APPROVED** [review]
